### ISSUE TITLE
Use a different regex for extracting mentions

### ISSUE THREAD

**Issue by bleistivt** [R-J/MentionsPlus#1]
The mentions parser of the UmlautMentionsFormatter uses the username validation regex.

The problem with this is, that mentions may not work for users if the validation regex was changed to a less permissive one.

For example, some of my users come from an imported phpBB database that allowed spaces in usernames.
I don't intend to allow them in vanilla, but if I don't change it to allow spaces, `"user name"` will not be mentioned.

This is also a problem with users from SSO plugins which circumvent the validation.

I'd suggest just using `[^ ]` and `DELIMITER.?DELIMITER` for names without spaces.

I'd also do a pull request, just wanted to hear your opinion first.

**Comment by R-J** [comment]
I do not understand what you mean by "I'd suggest just using [^ ] and DELIMITER.?DELIMITER for names without spaces."
To my opinion I have to define what are possible username characters and what are not. If a space is a character that can be in a username, it must be in the regex, too.

I see the problem with not wanting to allow a character _any more_ which will cause troubles for the formatter. So if I had to solve that problem on my own, I'd no longer use c('Garden.User.ValidationRegex') but would add 

```
if (!c('MentionsPlus.ValidationRegex')) {
    saveToConfig('MentionsPlus.ValidationRegex', c('Garden.User.ValidationRegex'', '\d\w_ äöüß'))
}
if (!c('MentionsPlus.ValidationLength')) {
    saveToConfig('MentionsPlus.ValidationLength', c('Garden.User.ValidationLength', '{3,20}'));
}
```

to setup() and use c('MentionsPlus.ValidationRegex') instead of c('Garden.User.ValidationRegex') throughout the plugin.

Since I haven't understood your solution, I leave it up to you to judge the more elegant way to solve that problem and I would be thankful for a PR!

**Comment by bleistivt** [comment]
My solution was basically not to use a validation regex at all, because to my understanding a valid mention is either:
- @ followed by a non-whitespace character
- @ followed by the start delimiter, any character and the end delimiter

Which would be:
`@([^"]\S+)\b|@"(.+?)"`
(With " as start and end delimiter)

**Comment by R-J** [comment]
Only non-whitespace characters would force you to write @"name-with-dash". That would suck for shortnames lile @"r-j" ;-)
But if you allow underscore, what other special characters? If my username would be "r.j." you would have to write @"r.j." while @r-j is okay. That's hard to explain to anyone. I still think using a customizable regex is better.

**Comment by bleistivt** [comment]
The regex I posted works a little different, you can check it out here:
https://regex101.com/r/vT6eQ8/1

**Comment by R-J** [comment]
If you look at the two last lines of your example you see that a dot as the last character would require quotes. I guess that's a problem you always have when a dot is an allowed character...

I'm not completely convinced, but  that might jut be because I thought using the Vanilla ValidationRegex was a brilliant idea ;-)

**Comment by bleistivt** [comment]
Oops, you're right I didn't notice that. I don't think there is a better solution than the word boundary though, plus it's an unlikely user name.

Putting the quoted one first makes it a little shorter:
`@"(.+?)"|@(\S+)\b`

I'll definitely fork it and report back once I tried it on my live site.

**Comment by bleistivt** [comment]
You can see what I've done here https://github.com/bleistivt/MentionsPlus/commit/9409e6dd2f04b82bd0b47c3387f721ddc0b3296c
It works well, but it changes some things (delimiters are auto-quoted and won't be displayed in the post) so it's probably not mergeable for you.
